/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaemtrie;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author EddiePricefield
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());
    private Trie trie = new Trie();
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        
        initComponents();
        
        listResultado.setModel( new DefaultListModel<String>() );
        
        textPaneTexto.setText( "" );
        adicionarTextoFormatado(
            "by sea sells she shells shore the by by shore she she sea ball pen chair",
            Color.WHITE, false, false
        );
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTexto = new javax.swing.JScrollPane();
        textPaneTexto = new javax.swing.JTextPane();
        painelPesquisa = new javax.swing.JPanel();
        lblBuscarPor = new javax.swing.JLabel();
        txtBuscarPor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollPaneResultado = new javax.swing.JScrollPane();
        listResultado = new javax.swing.JList<>();
        btnLimpar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em Trie");

        textPaneTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPaneTextoKeyReleased(evt);
            }
        });
        scrollPaneTexto.setViewportView(textPaneTexto);

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        lblBuscarPor.setText("Buscar por:");

        txtBuscarPor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarPorKeyPressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Procurar pela palavra no texto");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        listResultado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneResultado.setViewportView(listResultado);

        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar caixa de texto");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnAbrir.setText("Abrir");
        btnAbrir.setToolTipText("Abrir documento .txt");
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesquisaLayout.createSequentialGroup()
                        .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPor)
                    .addComponent(txtBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpar)
                    .addComponent(btnAbrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneTexto))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String busca = txtBuscarPor.getText().trim().toLowerCase();
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
        model.clear();

        if (busca.isEmpty()) {
            String textoAtual = textPaneTexto.getText();
            textPaneTexto.setText("");
            adicionarTextoFormatado(textoAtual, Color.WHITE, false, false);
            return;
        }

        String textoCompleto = textPaneTexto.getText().replace("\r", "");
        trie.clear();
        textPaneTexto.setText("");
        
        //Eu tentei tanto regex diferente pra fazer com que uma palavra colada em uma pontuação funcionasse... no final, preferi adicionar cada simbolo individualmente porque MEUDEUS cara que negócio chatoooo
        String[] palavras = textoCompleto.split(" +|(?<=[.,:;=\\-*()\\[\\]{}\\?])|(?=[.,:;=\\-*()\\[\\]{}\\?])"); //Botei todos os simbolos porque sim não me julga
        for (int i = 0; i < palavras.length; i++) {
            String p = palavras[i];
            if (p.toLowerCase().equals(busca)) {
                adicionarTextoFormatado(p, new Color(75, 120, 175), true, true);
            } else {
                adicionarTextoFormatado(p, Color.WHITE, false, false);
            }

            if (i < palavras.length - 1) {
                if (p.matches("[.]") && palavras[i + 1].matches("[0-9]+")) { //Para valores do tipo 10.0
                }
                
                else if (p.matches("[-]") && palavras[i - 1].matches("[\\p{L}]+")) {// Para palavras com hífen, porque fui pensar nisso depois e real tava botando espaço depois de todos os - :D
                }
                
                else if (!(palavras[i + 1].matches("[.,:;=\\-*()\\[\\]{}\\?]")) && !p.matches("[\\[\\{\\(]")){// Verifica se o próximo e o atual nas listas de simbolos... Talvez faltou algum
                    adicionarTextoFormatado(" ", Color.WHITE, false, false);
                }
            }
        }
        
        List<Posicao> resultados = trie.buscar(busca);

        if (resultados.isEmpty()) {
            model.addElement("Palavra não encontrada");
        } else {
            for (Posicao pos : resultados) {
                model.addElement(pos.toString());
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarPorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorKeyPressed
        
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnBuscarActionPerformed(null);
        }
        
    }//GEN-LAST:event_txtBuscarPorKeyPressed

    private void textPaneTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPaneTextoKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
            if (textPaneTexto.getText().equals("")) {
                adicionarTextoFormatado(" ", Color.WHITE, false, false);
                textPaneTexto.setText("");
            }
        }
    }//GEN-LAST:event_textPaneTextoKeyReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
        model.clear();
        adicionarTextoFormatado(" ", Color.WHITE, false, false);
        textPaneTexto.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        javax.swing.JFileChooser buscador = new javax.swing.JFileChooser();

        javax.swing.filechooser.FileNameExtensionFilter filtro
                = new javax.swing.filechooser.FileNameExtensionFilter("Arquivos de Texto (.txt)", "txt");
        buscador.setFileFilter(filtro);
        buscador.setAcceptAllFileFilterUsed(false);

        int resultado = buscador.showOpenDialog(this);

        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File arquivoSelecionado = buscador.getSelectedFile();

            try {
                String conteudo = java.nio.file.Files.readString(arquivoSelecionado.toPath());

                trie.clear();
                textPaneTexto.setText("");

                adicionarTextoFormatado(conteudo, Color.WHITE, false, false);

            } catch (java.io.IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível ler o arquivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void adicionarTextoFormatado( String texto, Color cor, boolean italico, boolean negrito ) {
        
        try {
            int posicaoInicial = textPaneTexto.getDocument().getLength();
            
            SimpleAttributeSet as = new SimpleAttributeSet();
            StyleConstants.setForeground( as, cor );
            StyleConstants.setBold( as, negrito );
            StyleConstants.setItalic( as, italico );
            
            textPaneTexto.getDocument().insertString( textPaneTexto.getDocument().getLength(), texto, as );
            
            String[] palavras = texto.split(" ");
            int deslocamento = 0;
            
            for (String p : palavras) {
                if (!p.isEmpty()) {
                    // A coluna real é a posição inicial no documento + o deslocamento da palavra
                    int colunaReal = posicaoInicial + deslocamento;
                    trie.inserir(p, 1, colunaReal);

                    // Atualiza o deslocamento para a próxima palavra (+1 do espaço)
                    deslocamento += p.length() + 1;
                }
            }
            
        } catch ( BadLocationException exc ) {
            exc.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new JanelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JList<String> listResultado;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JScrollPane scrollPaneResultado;
    private javax.swing.JScrollPane scrollPaneTexto;
    private javax.swing.JTextPane textPaneTexto;
    private javax.swing.JTextField txtBuscarPor;
    // End of variables declaration//GEN-END:variables
}
